name: ridy
description: Rider Application of Taxi

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+110

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  artemis: 7.2.6-beta
  auto_size_text: ^3.0.0
  client_shared:
    path: ../../libs/client-shared
  country_code_picker: ^2.0.2
  country_codes: ^2.2.0
  dots_indicator: ^2.1.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  file_picker: ^4.5.1
  firebase_analytics: ^9.1.8
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  firebase_messaging: ^11.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_types: ^3.3.4
  flutter_chat_ui: ^1.5.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^3.1.0
  flutter_rating_bar: ^4.0.0
  flutter_vector_icons: ^1.0.0
  geolocator: ^8.2.1
  google_fonts: ^2.3.2
  gql: 0.13.1-alpha+1635149947792
  graphql_flutter: ^5.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  lifecycle: ^0.4.3
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.1
  motion_sensors: ^0.1.0
  osm_nominatim: ^2.0.1
  package_info_plus: ^1.4.0
  pinput: ^2.2.16
  shimmer: ^2.0.0
  timeago_flutter: ^1.1.0
  url_launcher: ^6.1.2
  velocity_x: ^3.4.0
  yandex_geocoder: ^2.0.2
  yandex_mapkit:
    git: https://github.com/SoftAtlas/yandex_mapkit.git

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
  # flutter_test:
  #   sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/expanding_marker.json
    - images/3532-car.json
    - images/marker_pickup.png
    - images/marker_taxi.png
    - images/marker_destination.png
    - images/searching.png
    - images/booking_confirmed.png
    - images/logo.png

flutter_intl:
  enabled: true
