name: ridy
description: Driver application of Ridy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+110

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  artemis: 7.7.0-beta
  assets_audio_player: ^3.0.5
  auto_size_text: ^3.0.0
  client_shared:
    path: ../../libs/client-shared
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.5
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  file_picker: ^4.5.1
  firebase_analytics: ^9.1.4
  firebase_auth: ^3.3.16
  firebase_core: ^1.14.0
  firebase_crashlytics: ^2.7.1
  firebase_messaging: ^11.2.15
  fl_chart: ^0.50.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_ui: ^1.5.8
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^3.1.0
  flutter_svg: ^1.0.3
  flutter_vector_icons: ^1.0.0
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  google_fonts: ^2.3.2
  graphql_flutter: ^5.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  lifecycle: ^0.4.4
  lottie: ^1.2.2
  map_launcher: ^2.1.2
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.1
  motion_sensors: ^0.1.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9
  shimmer: ^2.0.0
  sms_autofill: ^2.1.0
  timeago_flutter: ^1.1.0
  url_launcher: ^6.1.0
  velocity_x: ^3.4.0
  yandex_mapkit:
    git: https://github.com/SoftAtlas/yandex_mapkit.git

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4
  json_serializable: ^6.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/QazaQGOdriver.png"

dependency_overrides:
  collection: 1.16.0
  path: ^1.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - images/
    - sounds/

flutter_intl:
  enabled: true
